### ISSUE TITLE
Hyperborder no longer works with hyper-2.0.0 canary 15

### ISSUE THREAD

**Issue by coreyjackwilson** [webmatze/hyperborder#43]
```
bundle.js:1 Error: Cannot find module '/Users/XXX/.hyper_plugins/node_modules/hyperborder'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/Applications/Hyper.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Function.c._load (file:///Applications/Hyper.app/Contents/Resources/app.asar/renderer/bundle.js:1:8001)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at D.e.plugins.concat.map (file:///Applications/Hyper.app/Contents/Resources/app.asar/renderer/bundle.js:1:8948)
    at Array.map (native)
    at D (file:///Applications/Hyper.app/Contents/Resources/app.asar/renderer/bundle.js:1:8899)
    at Object.<anonymous> (file:///Applications/Hyper.app/Contents/Resources/app.asar/renderer/bundle.js:1:10452)
```

**Comment by webmatze** [comment]
Thanks for the report. I will take a look at it.

**Comment by zenorocha** [comment]
Just updated to Hyper 2 stable and it's not working too.

**Comment by Xapphire13** [comment]
Some discussion [here](https://github.com/zeit/hyper/issues/2826)

**Comment by slhodson969** [comment]
Same here. Updated to Hyper 2.0.0 and have had to disable this plugin.

**Comment by Meesayen** [comment]
@webmatze this is what I ended up with https://github.com/Meesayen/hyperborder/commit/5823d9672d27402641235d1420926f3bb870f317

Basically the use of CSS custom properties was making Hyper crash and adding CSS rules to html and body doesn't seem to work anymore in v2.0.

I hope this helps you find a better solution, my commit is just a quick and dirty one. :v:

**Comment by webmatze** [comment]
I am also working on it. Unfortunately, the injected CSS is now automatically prefixed with `#hyper` so we can not change the styles of the **HTML** or **BODY** tags anymore without wild hacks.

@Meesayen I will look into your changes.

**Comment by webmatze** [comment]
I just created a PR with Hyper 2 compatibility! Would be great if someone could test it first.
