### PR TITLE
Hyper2 compatibility

### LINKED ISSUE #43: Hyperborder no longer works with hyper-2.0.0 canary 15
```
bundle.js:1 Error: Cannot find module '/Users/XXX/.hyper_plugins/node_modules/hyperborder'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/Applications/Hyper.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Function.c._load (file:///Applications/Hyper.app/Contents/Resources/app.asar/renderer/bundle.js:1:8001)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at D.e.plugins.concat.map (file:///Applications/Hyper.app/Contents/Resources/app.asar/renderer/bundle.js:1:8948)
    at Array.map (native)
    at D (file:///Applications/Hyper.app/Contents/Resources/app.asar/renderer/bundle.js:1:8899)
    at Object.<anonymous> (file:///Applications/Hyper.app/Contents/Resources/app.asar/renderer/bundle.js:1:10452)
```

### PR DESCRIPTION
**Pull request by webmatze**
This fixes the problems with version 2 of the Hyper app.

fixes #43

### CODE REVIEW

**Comment by webmatze** [comment]
All features are working again. I did a major refactoring of the code.

We are now introducing an own wrapper Node around the `<hyper>` node and use it for styling. That way we can inject our own styles.

Great thing is, this works both with older and newer versions of the Hyper app.
